### ISSUE TITLE
USER STORY: Create Header & Navigation

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#1]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 1 | Design Header |
| User Story 1 | As a user, I want a clean, user-friendly header at the top of the page so that I can easily navigate and access the key features of the system. |
| Story Points | 2 |

## Description
**As a** user

**I want** a clean, user-friendly header at the top of the page

**So that** I can easily navigate and access the key features of the system.

## Acceptance Criteria
1. Add to navbar elements properly linking the key features as shown on the skeleton plane
2. Use Materialize this time to create a cleaner layout and interaction
3. Use submenus if needed for example for the Support section

## Tasks
- [x] Install Bootstrap template and create a custom CSS file to override or add our styles.
- [x] Implement navbar for big screens and mobile, consider submenus.
- [x] Link to the system functionality described on the menu as seen on the skeleton plane.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
