### ISSUE TITLE
USER STORY: Build Footer & Extra info

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#11]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 5 | Construct Footer |
| User Story 1 | As a user, I want to scroll to the end of the page to see the footer so that I have access to extra key information, useful links, and legal data. |
| Story Points | 2 |

## Description
**As a** User,

**I want** to scroll to the end of the page to see the footer,

**So that** I have access to extra key information, useful links, and legal data.

## Acceptance Criteria
1. Implement sections for relevant data
2. Add about part section, useful links, and social media
3. Build it so that it matches the overall design

## Tasks
- [x] Use a template for the footer that will hold the relevant data & add real data instead
- [x] Make sure the division is clear, about, useful links & social media
- [x] Use the same relevant classes already used to keep consistency in the design

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All completed, more links will be added later
