### ISSUE TITLE
USER STORY: Design 'Sign in/sign up' from Header

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#12]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic 1 | Link & Page from Header |
| User Story 1 | As a user or admin, I want to click on the header 'sign in/sign up' and be able to validate my login details on a separate page so that I can access my dashboard. |
| Story Points | 1 |

## Description
**As a** User or Admin,

**I want**  to click on the header 'sign in or sign up' and be able to validate my login details on a separate page,

**So that**  I can access my dashboard.

## Acceptance Criteria
1. Make sure the links are working
2. Make sure the form is working
3. Make sure the form is redirecting to the user or admin dashboard

## Tasks
- [x] Link up the login & signup features to the header, use submenus if neccessary
- [x] Confirm that the login form & signup form is working
- [x] Verify that the users are being properly redirected to their dashboards based on user's role

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Completed 100%
