### ISSUE TITLE
USER STORY: Create Login/sign up & Dashboard

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#13]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic 2 | Create User & Admin Dashboard |
| User Story 1 | As a user or admin, I want to log in and signup so that I can find a useful dashboard with key stats & menu options, based on my role, to interact with the system securely and smoothly. |
| Story Points | 7 |

## Description
**As a** User or Admin,

**I want** to log in and signup,

**So that** I can find a useful dashboard with key stats & menu options, based on my role, to interact with the system securely and smoothly.

## Acceptance Criteria
1. Develop Database Models, taking into account roles
2. Adapt the Admin Panel template that will work as a Dashboard for Users and Admins
3. Settle all down for the next user stories that will need this functionality

## Tasks
- [x] Task 1: Develop Database model on models.py, use ERD as guidance
- [x] Task 2: Install SB Admin Panel with Bootstrap 5 and customize it for our needs
- [x] Task 3: Allow for scalability for the next steps to follow

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Ensure AdminRequiredMixin  & UserRequiredMixin on features to divide Admin & User Dashboard

**Comment by plexosoft** [comment]
Admin can create Vote Cards and select card status from the admin panel
