### ISSUE TITLE
USER STORY: Add Profile Settings on Dashboard

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#14]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic 3 | Build User & Admin Profile Settings |
| User Story 1 | As a user or admin, I want to find a section on the dashboard to edit and control my profile on the system, to have full control over my data, and protect my privacy. |
| Story Points | 7 |

## Description
**As a** User or Admin,

**I want** to find a section on the dashboard to edit and control my profile on the system,

**So that** I have full control over my data, and protect my privacy.

## Acceptance Criteria
1. Include on the Side Bar Menu a Profile section
2. Add in this profile section a form to fetch and edit profile data, the official name cannot be modified, and read-only for data of that nature
3. Add an option for account deletion only when no participation at all or when the records have been deleted

## Tasks
- [x] Create dedicated profile settings on the dashboard, accessible from the menu sidebar
- [x] Open up a form that fetches current data and displays some read-only data for verified users
- [x] Add an option and warning for account deletion only when no participation at all or when the records have been deleted

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
CREATE, READ & UPDATE for dashboard settings added. 

- DONE: development for passwords for both Admin & User side & Validation
- DONE: Include Bootstrap module for deletion, clarify that all data will be deleted including data records to protect system integrity

**Comment by plexosoft** [comment]
Ensure AdminRequiredMixin  & UserRequiredMixin on features to divide Admin & User Dashboard
