### ISSUE TITLE
USER STORY: Implement account verification & badges

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#15]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic 4 | Implement Verification Badge |
| User Story 1 | As a user or admin, I want to verify my account via email or KYC, to get access to a verified badge and participate in certain voting events. |
| Story Points | 4 |

## Description
**As a** User or Admin,

**I want** to verify my account via email or KYC,

**So that** I get access to a verified badge and participate in certain voting events.

## Acceptance Criteria
1. Design the email verification process accessible from the User & Admin Dashboard
2. Create a friendly section for email verification
3. Design a badge system based on the user's role

## Tasks
- [ ] Start with email verification and use the 'verified' attribute on the user's model (boolean)
- [ ] Build an email verification section for the user's side that shows the current status and a button to resubmit verification
- [ ] Design based on the user's role the logic and graphics to assign badges depending on the current 'role' & 'verified' values.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Back to the main board since we face time related constraint, not relevant for this iteration
