### ISSUE TITLE
USER STORY: Build Event Creation for User & Admin

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#17]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic 1 | Establish User & Admin Event Creation |
| User Story 1 | As a user or admin, I want to create voting events from my dashboard and make them visible on the homepage once I have been verified, to make use of the powerful voting system. |
| Story Points | 7 |

## Description
**As a** User or Admin,

**I want**  to create voting events from my dashboard and make them visible on the homepage once I have been verified,

**So that** I can make use of the powerful voting system.

## Acceptance Criteria
1. Make sure once the user has been verified to allow vote card creation
2. Assure that vote cards creation requires approval from the admin side
3. Add to the menu the 'Events' Management section and its dedicated page

## Tasks
- [x] Make sure the database model works properly for the user roles and account verification
- [x] Apply conditional CRUD functionality to read and create voting events.
- [x] Set up the environment for the back-end (form) and front-end visibility

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Task 1: Account verification is out of the scope of this project. The database model works properly.

**Comment by plexosoft** [comment]
READ for user & admin on dashboard completed.

**Comment by plexosoft** [comment]
'Apply conditional CRUD functionality to read and create voting events.': Expiration alerts for vote cards added: active, today, expired

**Comment by plexosoft** [comment]
Ensure AdminRequiredMixin  & UserRequiredMixin on features to divide Admin & User Dashboard
