### ISSUE TITLE
USER STORY: Design Voting Page & Connect to Related Content Structure

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#18]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic 2 | Design Voting Page |
| User Story 1 | As a user, I want to see voting events and participate, I can also click on 'Vote' to start the voting process on a separate page to have a more comprehensive section related to the event, seeing information not available on the homepage. |
| Story Points | 7 |

## Description
**As a** User,

**I want** to see voting events and participate, I can also click on 'Vote' to start the voting process on a separate page

**So that** I have a more comprehensive section related to the event, seeing information not available on the homepage.

## Acceptance Criteria
1. Implement a voting system on the single voting page
2. Load the list of candidates and submit your choice with the 'Vote' button
3. Make sure the model and views support this action, the form needed
4. Display votes on user's vote on dasboard

## Tasks
- [x] Verify that the model can support these features
- [x] Create a view with logic for this to create a VoteRecord
- [x] Manual test and changes based on final functionality, use different resources for guidance
- [x] Implement data display on the user & admin dashboard (My votes)

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All completed, styled and connected
