### ISSUE TITLE
USER STORY: Enable Feedback after voting

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#19]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic 3 | Enable Voting Feedback |
| User Story 1 | As a user, I want to see a success alert or message after voting on an event as well as an update about the current stats, to have a better perception of the event situation and my contribution. |
| Story Points | 7 |

## Description
**As a** User,

**I want** to see a success alert or message after voting on an event as well as an update about the current stats,

**So that** I have a better perception of the event situation and my contribution.

## Acceptance Criteria
1. Implement logic to emit a success messages and vote count update
2. Make sure there is error handling and other messages included
3. Use proper box & styling keeping layout consistency

## Tasks
- [x] Use the Django library 'messages' to handle this
- [x] Implement conditional statements on the templates for a more robust functionality 
- [x] Keep using bootstrap style 'card' for more consistency

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All implemented on time
