### ISSUE TITLE
USER STORY: Design Campaign row & Sortation

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#2]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 2 | Arrange Mixed Campaign Cards in Row |
| User Story 1 | As a user, I want to see a general campaign section displayed prominently under the header, providing a recent mix of 'official' and 'community' created campaigns so that I can quickly overview current campaigns.|
| Story Points | 4 |

## Description
**As a** User

**I want**  to see a general campaign section displayed prominently under the header, providing a recent mix of 'official' and 'community' created campaigns

**So that** I can quickly overview current campaigns.

## Acceptance Criteria
1. Make sure the title 'Campaign' is before the cards display
2. Follow the skeleton & surface section
3. Apply the necessary logic to display a mix of both categories

## Tasks
- [x] Solve the issue with the VoteCard module to include the 2 options for 'Official' & 'Campaign'
- [x] Implement cards and styles using the template chosen, customize if where needed
- [x] Use Jinja template language for the logic where needed

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Task completed, new styles applied, logic for votes used & added to the DB model what was needed
