### ISSUE TITLE
USER STORY: Develop Voting Counter & Timer for Cards

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#20]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic 4 | Develop Voting Counter & Timer |
| User Story 1 | As a user, I want to see a Vote Count & Progress Bar (time-related) on the homepage for each voting card and on the single page, to know how many people have participated and how much time is left for the event to end. |
| Story Points | 13 |

## Description
**As a** User,

**I want** to see a Vote Count & Progress Bar (time-related) on the homepage for each voting card and on the single page,

**So that** I know how many people have participated and have visual feedback about how much time is left for the event to end.

## Acceptance Criteria
1. Implement a progress bar and vote counter as seen on the skeleton
2. Make sure it appears on all instances of single cards (different pages)
3. Read necessary documentation and implement features

## Tasks
- [x] Use Bootstrap for both features
- [x] Update changes to all  public instances of the voting card
- [x] Use VoteCardBaseListView, timezone Django import & implement logic based on duration and time elapsed, then connect to the bootstrap progress bar

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Logic has been completed for the vote cards displayed on the homepage, now we need to focus on the single list view

**Comment by plexosoft** [comment]
All completed, styled and structured
