### ISSUE TITLE
USER STORY: Configure Role Visualization on the Dashboard

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#21]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic 5 | Configure Role Visualization |
| User Story 1 | As a user, visitor, or admin, I want to have a visual understanding of my privileges depending on my role, to grasp the full potential of the site. |
| Story Points | 4 |

## Description
**As a** user, visitor, or admin,

**I want** to have a visual understanding of my privileges depending on my role,

**So that** I grasp the full potential of the site.

## Acceptance Criteria
1. Make sure the 'Role' section can be found on the user and admin's dashboard
2. Display in this section the current role, information, and badge
3. Discuss the necessity of new columns on the database model

## Tasks
- [x] Include the Role section on both Dashboards, one for display and the other for management if needed
- [x] Fetch and display proper data related to the current role, privileges & badge 
- [x] Use role entry on the database model to determine privileges info and badges

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
The environment has been set, and data structure is needed. Tomorrow will be done.

**Comment by plexosoft** [comment]
User Role display DONE

**Comment by plexosoft** [comment]
Admin Role display DONE
