### ISSUE TITLE
USER STORY: Develop 'See More' Page

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#22]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Search & Filter |
| Epic 1 | Develop 'See More' Page |
| User Story 1 | As a user, I want to see a 'see more' button after each section on the homepage which will take me to another page where I can see all the active events. |
| Story Points | 4 |

## Description
**As a** User,

**I want** to see a 'see more' button after each section on the homepage which will take me to another page,

**So that** I can see all the active events.

## Acceptance Criteria
1. Build a view with pagination for the sections
2. Make sure the voting cards are being filtered properly
3. Modify model variables if needed

## Tasks
- [x] Create a view and template for the see more section
- [x] Use jinja language for filtering on the frontend and use Django methods on views for robustness
- [x] Consider targeting the Type & Status of the voting card for filtering

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All completed satisfactorily
