### ISSUE TITLE
USER STORY: Build Publisher approval system for Admin

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#28]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | KYC |
| Epic 3 | Authorize Publisher Role |
| User Story 2 | As a user with a publisher role, I want to create events once verified, but still need approval from the admin side, for my voting event to be published. |
| Story Points | 7 |

## Description
**As a** Publisher,

**I want** to create events once verified, but still need approval from the admin side,

**So that** my voting event can be published.

## Acceptance Criteria
1. Include on the admin dashboard an Events Approval section
2. Make sure that a user's voting cards are approved upon POSTING
3. Once approved the card will be updated and published immediately on the front end if 'Online'

## Tasks
- [x] Add on the admin dashboard the Event Approval section
- [x] Add form to fetch and analyze vote card data and the status section as 'select' element
- [x] Use the status entry integers to deal with the status
- [x] Update status on the database after POST

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All completed by refactoring and reusing code
