### ISSUE TITLE
USER STORY: Construct Contact Page & Form

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#29]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Accountability |
| Epic 1 | Construct Contact Form |
| User Story 1 | As a user, I want a well-designed contact page to get in touch with the support team. |
| Story Points | 2 |

## Description
**As a** User,

**I want** a well-designed contact page,

**So that** I can get in touch with the support team.

## Acceptance Criteria
1. Use a proper design for consistency
2. Connect to the EmailJS service for a functional contact form
3. Make sure user feedback and validation are active

## Tasks
- [x] Use Bootstrap to create the form faster
- [x] Use EmailJS and its documentation to adjust it accordingly
- [x] Use Javascript for user feedback

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All completed and functional
