### ISSUE TITLE
USER STORY: Display Key Information on the 'Campaign' Voting Card

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 2 | Arrange Mixed Campaign Cards in Row |
| User Story 2 | As a user, I want each card to display key information in the 'Campaign' section related to the event, so I understand what I'm clicking on. |
| Story Points | 2 |

## Description
**As a** User

**I want** each card to display key information related to the event

**So that** I understand what I'm clicking on.

## Acceptance Criteria
1. Make sure the data displayed complies we our plan
2. Take into account simplicity and priority to the eye
3. Display data as seen on the skeleton & refer to the mindmaps & data models for the data structure

## Tasks
- [x] Use documentation created so far to guide yourself and compare with
- [x] Make sure data is displayed in a clean manner and easy to read, consider data base constraints for the number of characters to display
- [x] Refer to the documentation material and database models directly

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
The single page for each card will be implemented in the next rounds
