### ISSUE TITLE
USER STORY: Assemble FAQ Page and Section

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#32]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Accountability |
| Epic 3 | Assemble FAQ Section |
| User Story 1 | As a user, I want to find a FAQ section on the support page, to see videos or articles for troubleshooting or other questions related to the voting system. |
| Story Points | 4 |

## Description
**As a** User,

**I want** to find a FAQ section on the support page,

**So that** I can see videos or articles for troubleshooting or other questions related to the voting system.

## Acceptance Criteria
1. Add in this section 'collapse' entries with answers as text or videos
2. Make sure the content is real and related to the system and project
3. Use Bootstrap to keep consistency with the rest of the design

## Tasks
- [x] Use Bootstrap 'collapse' to show and hide information
- [x] Use real content for the entries or questions
- [x] Use Bootstrap design to keep consistency, keep it simple 

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All set up and completed on time
