### ISSUE TITLE
USER STORY: Event results, event update and calculation

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#34]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Voting system |
| Epic # | 'Display winner and general results with numbers' |
| User Story # | **As a** User **I want** to see displayed in a structured manner the winner, the challengers, and the vote numbers **So that** I have a transparent view of the event, especially for tied results. |
| Story Points | 7 |

## Description
**As a** User

**I want** to see displayed in a structured manner the winner, the challengers, and the vote numbers

**So that** I have a transparent view of the event, especially for tied results.

## Acceptance Criteria
1. Implement in the single vote card all these features keep the rule of 3 for the progressive disclosure
2. Make sure the model is supporting these features specifically for the expiration date
3. On the template apply the necessary logic to display what's actually happening based on users' inputs

## Tasks
- [x] Reuse HomePageSingleView and work in there, create another view if required
- [x] On the VoteCard model add a method to set the vote as completed based on the expiration date
- [x] Use different statements to provide data based on the VoteCard status and results, pay attention to those candidates with tied results, display them too

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Tiding up frontend

**Comment by plexosoft** [comment]
All completed: Count Django import used
