### ISSUE TITLE
USER STORY: Include See More button under Campaigns row

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#4]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 2 | Arrange Mixed Campaign Cards in Row |
| User Story 3 | As a user, I want to see a 'see more' button under the 'Campaigns' section so that I can view more comprehensive results on a separate page. |
| Story Points | 1 |

## Description
**As a** User

**I want** to see a 'see more' button under the 'Campaigns' section

**So that** I can view more comprehensive results (more cards) on a separate page.

## Acceptance Criteria
1. Develop a friendly 'see more' button under the Campaign section
2. This section should show all available cards for this section (mixed cards)
3. Make sure to use pagination to develop it faster

## Tasks
- [x] Use bootstrap buttons to achieve the requested development
- [x] Make sure 6 cards per page if more then use pagination
- [x] Verify that the view is actually displaying 6 and not 3

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
To tackle this issue we had to create a new view in the vote_management app called BaseListViewDetailed

**Comment by plexosoft** [comment]
It was achieved in time record
