### ISSUE TITLE
USER STORY: Add Official row beneath the Campaign row

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#5]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 3 | Present Official Cards in Row |
| User Story 1 | As a user, I want to see an 'Official' section beneath the 'Campaign' row, presenting single-related events so that I can preview events related to this category. |
| Story Points | 4 |

## Description
**As a** User

**I want** to see an 'Official' section beneath the 'Campaign' row, presenting single-related events

**So that** I can preview events related to this category.

## Acceptance Criteria
1. Make sure the data displayed complies we our plan
2. Take into account simplicity and priority to the eye
3. Display data as seen on the skeleton & refer to the mindmaps & data models for the data structure

## Tasks
- [x] Use documentation created so far to guide yourself and compare with
- [x] Make sure data is displayed in a clean manner and easy to read, consider database constraints for the number of characters to display
- [x] Refer to the documentation material and database models directly

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Reused the Campaign section to implement this user story, used templating language to filter out only Official cards.
