### ISSUE TITLE
USER STORY: Display Key Information on the 'Community' Voting Card

### ISSUE THREAD

**Issue by plexosoft** [plexoio/musa#9]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic 4 | Display Community Cards in Row |
| User Story 2 | As a user, I want each card to display key information in the 'Community' section related to the event, so I understand what I'm clicking on. |
| Story Points | 2 |

## Description
**As a** User,

**I want** each card to display key information in the 'Community' section related to the event,

**So that** I understand what I'm clicking on.

## Acceptance Criteria
1. Create a single page for each vote card
2. Include more information on each page including a list of the candidates
3. Make sure the layout has been set for the voting part of the system

## Tasks
- [x] Reuse view and template for the single vote card page
- [x] Display the candidates  as well for more visual development
- [x] Style, center, and display extra data about de VoteCard not included on the homepage as before

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
All tasks completed reusing the logic from previous instances
